## playing with names

In [1]:
names = open('names.txt', 'r').read().splitlines()
names[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
m1 = min(len(name) for name in names)
m2 = max(len(name) for name in names)
m1, m2

(2, 15)

## counting

In [20]:
DOT = '.'
chars = ['.'] + sorted(list(set(''.join(names))))
print(chars)

stoi = {s: i for i, s in enumerate(chars)}
print(stoi)
itos = {i: s for s, i in stoi.items()}
print(itos)

for name in names[:2]:
    name = DOT + name + DOT
    for c1, c2 in zip(name, name[1:]):
        print(c1, c2)

['.', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
{'.': 0, 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}
{0: '.', 1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z'}
. e
e m
m m
m a
a .
. o
o l
l i
i v
v i
i a
a .


In [21]:
import torch

In [ ]:
# torch.Size([2]) 和 torch.Size([2, 1]) 的区别是：前者是一维向量，后者是二维矩阵，只是第二维长度为 1。

# 用具体值看：

# a = torch.tensor([
#     [1, 2, 3],
#     [4, 5, 6],
# ])

# s1 = torch.sum(a, dim=1)
# print(s1)
# print(s1.shape)

# 输出：

# tensor([ 6, 15])
# torch.Size([2])

# 这是 1D tensor：

# [6, 15]

# 而：

# s2 = torch.sum(a, dim=1, keepdim=True)
# print(s2)
# print(s2.shape)

# 输出：

# tensor([[ 6],
#         [15]])
# torch.Size([2, 1])

# 这是 2D tensor：
#
# [
# [6],
# [15]
# ]

# 可以这样理解：

# torch.Size([2])    -> 只有一个轴，长度为 2
# torch.Size([2, 1]) -> 有两个轴，第 0 维长度为 2，第 1 维长度为 1

# 为什么需要保留 [2, 1]？主要是为了后续 broadcasting。
a = torch.randn(4, 4)
print(a)
print(torch.sum(a, 1, keepdim=True))
print(torch.sum(a, 1, keepdim=True).shape)
print(torch.sum(a, 1, keepdim=False))
print(torch.sum(a, 1, keepdim=False).shape)
print(torch.sum(a))

tensor([[-2.0630,  0.4745, -0.0958,  1.3236],
        [ 0.2148,  0.0492,  0.2239,  1.5848],
        [ 0.3259, -0.6465,  0.7201, -0.3991],
        [ 0.3058, -0.4903,  0.3750,  0.4661]])
tensor([[-3.6072e-01],
        [ 2.0726e+00],
        [ 3.2309e-04],
        [ 6.5663e-01]])
torch.Size([4, 1])
tensor([-3.6072e-01,  2.0726e+00,  3.2309e-04,  6.5663e-01])
torch.Size([4])
tensor(2.3688)


In [64]:
# 27 * 27 matrix for transition counts
counting = torch.ones((len(chars), len(chars)), dtype=torch.int32)

for name in names:
    name = DOT + name + DOT
    for c1, c2 in zip(name, name[1:]):
        i, j = stoi[c1], stoi[c2]
        counting[i, j] += 1

print(counting)

# convert to probabilities
probs = counting.float()
probs /= probs.sum(1, keepdim=True)
print(probs[0])

tensor([[   1, 4411, 1307, 1543, 1691, 1532,  418,  670,  875,  592, 2423, 2964,
         1573, 2539, 1147,  395,  516,   93, 1640, 2056, 1309,   79,  377,  308,
          135,  536,  930],
        [6641,  557,  542,  471, 1043,  693,  135,  169, 2333, 1651,  176,  569,
         2529, 1635, 5439,   64,   83,   61, 3265, 1119,  688,  382,  835,  162,
          183, 2051,  436],
        [ 115,  322,   39,    2,   66,  656,    1,    1,   42,  218,    2,    1,
          104,    1,    5,  106,    1,    1,  843,    9,    3,   46,    1,    1,
            1,   84,    1],
        [  98,  816,    1,   43,    2,  552,    1,    3,  665,  272,    4,  317,
          117,    1,    1,  381,    2,   12,   77,    6,   36,   36,    1,    1,
            4,  105,    5],
        [ 517, 1304,    2,    4,  150, 1284,    6,   26,  119,  675,   10,    4,
           61,   31,   32,  379,    1,    2,  425,   30,    5,   93,   18,   24,
            1,  318,    2],
        [3984,  680,  122,  154,  385, 1272,   83,

In [65]:
print(sum(probs[6]))

tensor(1.)


In [69]:
print(probs)

tensor([[3.1192e-05, 1.3759e-01, 4.0767e-02, 4.8129e-02, 5.2745e-02, 4.7785e-02,
         1.3038e-02, 2.0898e-02, 2.7293e-02, 1.8465e-02, 7.5577e-02, 9.2452e-02,
         4.9064e-02, 7.9195e-02, 3.5777e-02, 1.2321e-02, 1.6095e-02, 2.9008e-03,
         5.1154e-02, 6.4130e-02, 4.0830e-02, 2.4641e-03, 1.1759e-02, 9.6070e-03,
         4.2109e-03, 1.6719e-02, 2.9008e-02],
        [1.9583e-01, 1.6425e-02, 1.5983e-02, 1.3889e-02, 3.0756e-02, 2.0435e-02,
         3.9809e-03, 4.9835e-03, 6.8796e-02, 4.8685e-02, 5.1899e-03, 1.6779e-02,
         7.4575e-02, 4.8213e-02, 1.6039e-01, 1.8872e-03, 2.4475e-03, 1.7988e-03,
         9.6279e-02, 3.2997e-02, 2.0288e-02, 1.1264e-02, 2.4623e-02, 4.7771e-03,
         5.3963e-03, 6.0480e-02, 1.2857e-02],
        [4.3039e-02, 1.2051e-01, 1.4596e-02, 7.4850e-04, 2.4701e-02, 2.4551e-01,
         3.7425e-04, 3.7425e-04, 1.5719e-02, 8.1587e-02, 7.4850e-04, 3.7425e-04,
         3.8922e-02, 3.7425e-04, 1.8713e-03, 3.9671e-02, 3.7425e-04, 3.7425e-04,
         3.1549e-

In [ ]:
# The bigram model is estimated from training counts:
#   counts[i, j] = how many times character j follows character i
#   probs[i, j] = P(j | i)
#
# When computing the NLL loss, we still evaluate every observed bigram occurrence,
# not only every unique (c1, c2) pair.
#
# This can look like "double counting" because probs are estimated from the same
# training data, then evaluated on that same data. But it is exactly the maximum
# likelihood objective:
#   likelihood = Π_t P(next_t | current_t)
#   log_likelihood = Σ_t log P(next_t | current_t)
#   nll = -mean_t log P(next_t | current_t)
#
# Therefore frequent bigrams must appear more times in the loss. For example, if
# a -> n appears 1000 times and a -> z appears 2 times, the loss should contain:
#   1000 * log P(n | a) + 2 * log P(z | a)
# Using set((c1, c2)) would remove frequency information and incorrectly give
# rare and frequent transitions the same weight.
#
# This counting bigram model is still a statistical/probability model, not a
# neural network: probs come directly from normalized counts, so there is no
# parameter gradient/update here. It mainly provides a baseline and introduces
# the language-modeling objective before the neural-network version.
xs , ys = [], []
for name in names:
    name = DOT + name + DOT
    for c1, c2 in zip(name, name[1:]):
        i, j = stoi[c1], stoi[c2]
        xs.append(i)
        ys.append(j)

bigram_prob = probs[xs, ys]
loss = -bigram_prob.log().mean()
print(loss)

tensor(2.4546)
